[package]
name = "zoo-debugger"
version = "0.1.0"
authors = ["jinnzoo <jinnzoo.pro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.17.0"
libc = "0.2.66"
clap = "2.20.3"
